spring:
  application:
    name: Config Center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/summerwind007/biz-config-file.git
          search-paths: /*
          force-pull: true
          #username:
          #password:

server:
  port: 9011

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
    instance-id: http://${eureka.instance.hostname}:${server.port}
    ip-address: ${eureka.instance.hostname}