spring:
  application:
    name: order-service
server:
  port: 9031
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
    instance-id: http://${eureka.instance.hostname}:${server.port}
    ip-address: ${eureka.instance.hostname}
